# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create Extension

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events only on specific branches
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create extensions
      run: ./package_extension.sh
    - name: Create source code zip file
      run: ./create_source_code_zip.sh
    - name: Temporarily save created output
      uses: actions/upload-artifact@v2
      with:
        name: extension-artifacts
        path: ./dist/*.zip
        retention-days: 14
